### ISSUE TITLE
Lava update broke building - Craft from Containers

### ISSUE THREAD

**Issue by Pontiac76** [aedenthorn/PlanetCrafterMods#9]
It seems like the mod is broken with the new release.  The object to be built is green, and whether or not the items are in ones inventory, you can't LMB or hit U to build the object.

I can hit the home key and I can see that it gets enabled and disabled, but, in either state, you just can't build anything

**Comment by aideya** [comment]
I actually cannot even open my inventory, or chests. I get an immediate crash error and the inventory window closes.

**Comment by Pontiac76** [comment]
Not sure what broke, but it seems to not be related to THIS particular mod.  Been running this fine.  Must be a conflict with something else.
